theme: minima
title: Self-Supervised Feature Learning by Learning to Spot Artifacts
author: Simon Jenni & Paolo Favaro
email: jenni@inf.unibe.ch, favaro@inf.unibe.ch
description: This is the project page for our CVPR2018 paper on self-supervised feature learning by learning to spot artifacts.
