theme: minima
title: Self-Supervised Feature Learning by Learning to Spot Artifacts
author: Simon Jenni & Paolo Favaro, University of Bern
email: jenni@inf.unibe.ch, favaro@inf.unibe.ch
description: This is the project page for our CVPR2018 spotlight paper titled "Self-Supervised Feature Learning by Learning to Spot Artifacts"
